In [1]:
### Numpy
### Numpy用于矩阵运算,只是工作中很多数据是以excel表格形式存在,而不是以矩阵存在,所以pandas更常用.但是pandas里面有大量的Numpy操作。


### 矩阵操作 其实可以理解成array数组操作,一维二维等形式不同而已，统称为数组
### 生成数组 np.array np.arange
### 特殊矩阵 zeros ones eye
### 随机数组 np.random.rand np.random.randn np.random.randint
### 从数组data中随机筛选size个元素,组成新的数组 np.random.choice() 
### 对数组参数重新打乱顺序 np.random.shuffle() 


### 数组的属性 shape size dtype ndim


### 数组元素获取 下标从0开始,倒序从-1开始


### 数据类型转换 astype
### 缺失值处理 isnan
### 重复值处理 unique
### 数组重塑:数组数据内容不变,对数据重新规划 reshape
### 数组转置 .T
  
    
### 数组合并 
### 横向合并 相当于left join ;横向合并,即追加列,行数都相同,列数不同  concatenate hstack column_stack
### 纵向合并 相当于union all ;纵向合并,即追加行,列数都相同,行数不同  concatenate hstack column_stack


### 常用分析函数
### 对数组内每一个元素进行处理  square平方 sqrt开方 abs绝对值 exp e(x)
### log、log10、log2、log1p 分别为自然对数（底数为e）、底数为10的log、底数为2的log、log(1+x)
### ceil向上取整 floor向下取整  rint四舍五入
### 数组整体、行、列 分别计算汇总值  sum mean算术平均数  average加权平均  median中位数 min max  std、var 
### np.percentile(data,95) #95%分位数


### 集合关系 唯一元素unique、交集intersect1d、并集union1d、包含in1d、差集setdiff1d、集合对称差 setxor1d

### 条件函数 np.where(condition,x,y) 类似于if(condition,x,y)
### 排序 sort
### all、any

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, date, time, timedelta
from pandas.tseries.offsets import Day,Hour,Minute
import sys
stdo = sys.stdout
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stdout= stdo

In [3]:
### 生成数组
print np.array([2,4,6,8,10]) ### [ 2  4  6  8 10] 
print np.array((2,4,6,8,10)) ### [ 2  4  6  8 10] 列表和元组都可以当参数
print len(np.array((2,4,6,8,10))) ### 长度为5
### 多维数组
arr1 = np.array(([2,4,6,8,10],[2,4,6,8,10])) 
print arr1
print len(arr1) ### 长度为2

[ 2  4  6  8 10]
[ 2  4  6  8 10]
5
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
2


In [4]:
### 参数start,end,step 其中 [start,end),start默认0,step默认1
print np.arange(0,15,1) ### 等同于 np.arange(15)
print np.arange(15)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
### 特殊矩阵 zeros ones eye
print np.zeros(4)
print np.zeros((4,5))
print np.ones(4)
print np.ones((4,5))
print np.eye(4) ### 一定是方阵,因为只有方针才有单位矩阵---对角线都是1,其余都是0

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
### 随机数组
print np.random.rand(5) ### (0,1)之间随机数组
print np.random.rand(4,5) ### (0,1)之间随机多维数组--随机矩阵
### randn 用于产生满足整体分布形状的随机数
print np.random.randn(5) ### 非0-1之间,但是保证正态分布
print np.random.randn(4,5) ### 非0-1之间,但是保证正态分布

[0.61794382 0.45773409 0.79169751 0.54470453 0.53916985]
[[0.81965581 0.98523819 0.87709186 0.69990843 0.05129769]
 [0.45834389 0.59275122 0.94433304 0.22333726 0.89807874]
 [0.62495862 0.01479399 0.72596368 0.60009449 0.40818283]
 [0.05067437 0.39029967 0.5365519  0.0289626  0.70757676]]
[-0.63007795  0.21836844 -1.59813424 -1.35174625  1.79686875]
[[-0.1561688   0.48698792 -0.1965828  -1.59557482 -2.58654457]
 [ 0.70136162 -0.01841266  0.35216654  1.05655039 -0.42415508]
 [ 0.29727246  0.4894556   1.11996393  0.32953278  0.1579939 ]
 [-0.17670407  1.41178399  0.04567715 -2.07881     0.39539006]]


In [7]:
### randint(start,end,size) 随机产生一定范围内的整数,注意:[start,end),size表示数组大小,
print np.random.randint(5,10,6) ### [5,10)之间产生6个随机整数
print np.random.randint(5,10,(4,5)) ### 产生2维数组
print np.random.randint(5,size = (4,5)) ### 没有填写start,表示start=0,输出内容是[0,5)

[9 9 9 6 6 6]
[[7 9 7 8 8]
 [8 7 7 6 5]
 [8 9 8 7 9]
 [7 8 5 5 6]]
[[0 4 2 0 2]
 [0 0 2 2 0]
 [1 0 2 0 3]
 [1 0 3 4 2]]


In [8]:
### 从数组data中随机筛选size个元素,组成新的数组 np.random.choice() 
### 参数 array,size,replace,p   注意:array可以是数组,也可以是整数,整数时表示先arange(int)生成数组.
print np.random.choice(5,size = 4) ### 随机找4个元素,生成一维数组
print np.random.choice(5,size = (4,5))  ###生成二维数组

[3 3 3 3]
[[0 2 3 1 3]
 [3 0 0 4 0]
 [0 2 3 0 0]
 [0 1 3 3 0]]


In [9]:
### 对数组参数重新打乱顺序 np.random.shuffle() 
arr2 = np.arange(10)
print arr2
np.random.shuffle(arr2)
print arr2

[0 1 2 3 4 5 6 7 8 9]
[4 0 7 6 3 1 5 9 2 8]


In [10]:
### 数组的属性 shape size dtype ndim
arr3 = np.random.randint(5,size = (4,5))
print arr3.shape ### shape形状,即多少维
print arr3.size ### 数组大小---提供多少个元素
print arr3.dtype ### 数组元素类型
print arr3.ndim ### 数组维度

(4, 5)
20
int64
2


In [11]:
### 数组元素获取 下标从0开始,倒序从-1开始
### 一维数组
arr2 = np.arange(10)
print arr2[0]
print arr2[-1]
print arr2[4:7]
print arr2[4:-2] ### 正序、倒序混用
print arr2[(arr2 >= 3) & (arr2 <= 7)] ### 条件筛选  返回元素满足判断条件的数据集合
print "-------"
### 多维数组
arr3 = np.random.randint(5,size = (4,5))
print arr3
print "-------"
print arr3[2:4] ### 获取某2整行数据
print arr3[:,2:4] ### 获取某2整列数据

0
9
[4 5 6]
[4 5 6 7]
[3 4 5 6 7]
-------
[[4 3 3 3 3]
 [1 0 3 4 1]
 [3 4 4 0 1]
 [4 0 2 0 3]]
-------
[[3 4 4 0 1]
 [4 0 2 0 3]]
[[3 3]
 [3 4]
 [4 0]
 [2 0]]


In [12]:
### 数据内容处理
### 数据类型转换 astype
arr3 = np.random.randint(5,size = (4,5))
print arr3.dtype
print arr3.astype(np.float64)
print arr3.astype(np.float64).dtype
print arr3.astype(np.string_)
print arr3.astype(np.string_).dtype

int64
[[4. 0. 4. 3. 0.]
 [1. 2. 3. 2. 1.]
 [0. 0. 4. 2. 2.]
 [1. 1. 1. 4. 2.]]
float64
[['4' '0' '4' '3' '0']
 ['1' '2' '3' '2' '1']
 ['0' '0' '4' '2' '2']
 ['1' '1' '1' '4' '2']]
|S21


In [13]:
### 缺失值处理 isnan
arr5 = np.array([1,2,np.nan,4])
print np.isnan(arr5) ### 判断是否有缺失值
arr5[np.isnan(arr5)] = 0 ### 获取缺失值,将其设置为0
print arr5

[False False  True False]
[1. 2. 0. 4.]


In [14]:
### 重复值处理 unique
arr5 = np.array([1,2,2,4,4])
print np.unique(arr5) ### 产生新的数组

[1 2 4]


In [15]:
### 数组重塑:数组数据内容不变,对数据重新规划 reshape
###一维数组
arr2 = np.arange(10)
print arr2.reshape(2,5) ### 产生新的数组 2行5列
print arr2
print "-----"
###二维数组
arr3 = np.random.randint(5,size = (4,5))
print arr3.reshape(5,4) ### 产生新的数组 2行5列
print "-----"
print arr3

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
-----
[[2 0 4 4]
 [0 0 3 1]
 [3 2 1 2]
 [3 1 2 1]
 [2 2 2 4]]
-----
[[2 0 4 4 0]
 [0 3 1 3 2]
 [1 2 3 1 2]
 [1 2 2 2 4]]


In [16]:
### 数组转置 .T
arr3 = np.random.randint(5,size = (4,5))
print arr3
print "-----"
print arr3.T

[[2 3 3 3 3]
 [4 1 0 1 0]
 [0 2 0 1 2]
 [1 0 3 1 2]]
-----
[[2 4 0 1]
 [3 1 2 0]
 [3 0 0 3]
 [3 1 1 1]
 [3 0 2 2]]


In [28]:
### 数组合并 
### 横向合并 相当于left join ;横向合并,即追加列,行数都相同,列数不同  concatenate hstack column_stack
arr3 = np.random.randint(5,size = (4,5))
arr4 = np.random.randint(5,size = (4,7))
print arr3
print "----"
print arr4
print "----"
print np.concatenate([arr3,arr4],axis = 1) ### 1表示横向合并
print "----"
print np.hstack((arr3,arr4)) ### 以元组为参数,不需要写 axis = 1
print "----"
print np.column_stack((arr3,arr4)) ### 以元组为参数,不需要写 axis = 1

[[4 1 4 1 3]
 [1 2 3 4 4]
 [1 1 0 3 2]
 [1 4 0 0 4]]
----
[[2 0 2 2 4 0 0]
 [2 4 3 1 3 0 2]
 [2 3 4 4 1 1 0]
 [4 1 3 4 3 2 4]]
----
[[4 1 4 1 3 2 0 2 2 4 0 0]
 [1 2 3 4 4 2 4 3 1 3 0 2]
 [1 1 0 3 2 2 3 4 4 1 1 0]
 [1 4 0 0 4 4 1 3 4 3 2 4]]
----
[[4 1 4 1 3 2 0 2 2 4 0 0]
 [1 2 3 4 4 2 4 3 1 3 0 2]
 [1 1 0 3 2 2 3 4 4 1 1 0]
 [1 4 0 0 4 4 1 3 4 3 2 4]]
----
[[4 1 4 1 3 2 0 2 2 4 0 0]
 [1 2 3 4 4 2 4 3 1 3 0 2]
 [1 1 0 3 2 2 3 4 4 1 1 0]
 [1 4 0 0 4 4 1 3 4 3 2 4]]


In [31]:
### 数组合并 
### 纵向合并 相当于union all ;纵向合并,即追加行,列数都相同,行数不同  concatenate hstack column_stack
arr3 = np.random.randint(5,size = (4,5))
arr4 = np.random.randint(5,size = (7,5))
print arr3
print "----"
print arr4
print "----"
print np.concatenate([arr3,arr4],axis = 0) ### 0表示纵向合并
print "----"
print np.vstack((arr3,arr4)) ### 以元组为参数,不需要写 axis = 1
print "----"
print np.row_stack((arr3,arr4)) ### 以元组为参数,不需要写 axis = 1

[[2 2 4 0 3]
 [2 1 4 3 3]
 [2 3 0 1 0]
 [4 1 4 1 4]]
----
[[1 2 2 0 3]
 [3 2 2 0 0]
 [0 3 4 3 4]
 [0 2 4 0 1]
 [3 1 0 1 3]
 [4 2 3 2 1]
 [0 1 4 2 4]]
----
[[2 2 4 0 3]
 [2 1 4 3 3]
 [2 3 0 1 0]
 [4 1 4 1 4]
 [1 2 2 0 3]
 [3 2 2 0 0]
 [0 3 4 3 4]
 [0 2 4 0 1]
 [3 1 0 1 3]
 [4 2 3 2 1]
 [0 1 4 2 4]]
----
[[2 2 4 0 3]
 [2 1 4 3 3]
 [2 3 0 1 0]
 [4 1 4 1 4]
 [1 2 2 0 3]
 [3 2 2 0 0]
 [0 3 4 3 4]
 [0 2 4 0 1]
 [3 1 0 1 3]
 [4 2 3 2 1]
 [0 1 4 2 4]]
----
[[2 2 4 0 3]
 [2 1 4 3 3]
 [2 3 0 1 0]
 [4 1 4 1 4]
 [1 2 2 0 3]
 [3 2 2 0 0]
 [0 3 4 3 4]
 [0 2 4 0 1]
 [3 1 0 1 3]
 [4 2 3 2 1]
 [0 1 4 2 4]]


In [18]:
### 常用分析函数
### 对数组内每一个元素进行处理  square平方 sqrt开方 abs绝对值 exp e(x)
### log、log10、log2、log1p 分别为自然对数（底数为e）、底数为10的log、底数为2的log、log(1+x)
### ceil向上取整 floor向下取整  rint四舍五入
arr3 = np.random.randint(5,size = (4,5))
print arr3
print "-----"
print np.square(arr3) ### 产生新的数组
print "-----"
print arr3

[[2 0 4 0 3]
 [4 4 1 2 4]
 [2 1 3 2 3]
 [3 0 3 3 1]]
-----
[[ 4  0 16  0  9]
 [16 16  1  4 16]
 [ 4  1  9  4  9]
 [ 9  0  9  9  1]]
-----
[[2 0 4 0 3]
 [4 4 1 2 4]
 [2 1 3 2 3]
 [3 0 3 3 1]]


In [19]:
### 常用分析函数
### 数组整体、行、列 分别计算汇总值  sum mean算术平均数  average加权平均  median中位数 min max  std、var
arr3 = np.random.randint(5,size = (4,5))
print arr3
print "-----"
print arr3.sum()
print arr3.sum(axis = 1) ### 行汇总
print arr3.sum(axis = 0) ### 列汇总

[[4 1 2 1 1]
 [2 0 2 3 1]
 [1 3 0 1 4]
 [4 0 1 0 2]]
-----
33
[9 8 9 7]
[11  4  5  5  8]


In [20]:
### 集合关系 唯一元素unique、交集intersect1d、并集union1d、包含in1d、差集setdiff1d、集合对称差 setxor1d
s0 = np.array([1,2,3,2,1,4,5,2])    # [1 2 3 2 1 4 5 2]
s1 = np.arange(0,30,2)  # [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
s2 = np.arange(0,30,3)  # [ 0  3  6  9 12 15 18 21 24 27]

### 唯一元素unique
print np.unique(s0) ### [1 2 3 4 5]

### 交集intersect1d
print np.intersect1d(s0,s1) ### [2 4]

### 并集union1d
print np.union1d(s0,s1) ### [ 0  1  2  3  4  5  6  8 10 12 14 16 18 20 22 24 26 28]

### 包含in1d
print np.in1d(s0,s1) ### 得到一个”s0的元素是否包含于s1”的布尔行数组 [False  True False  True False  True False  True]
print s0[np.in1d(s0,s1)] ### 从而可以过滤数据  [2 2 4 2]

### 差集 setdiff1d 与包含相反,表示s0元素不在s1中的
print np.setdiff1d(s0,s1) ### [1 3 5]

### 集合对称差 setxor1d 只存在x和y中的元素集合,即非公共部分的数据
print np.setxor1d(s0,s1) ### [ 0  1  3  5  6  8 10 12 14 16 18 20 22 24 26 28]

[1 2 3 4 5]
[2 4]
[ 0  1  2  3  4  5  6  8 10 12 14 16 18 20 22 24 26 28]
[False  True False  True False  True False  True]
[2 2 4 2]
[1 3 5]
[ 0  1  3  5  6  8 10 12 14 16 18 20 22 24 26 28]


In [21]:
### 条件函数 np.where(condition,x,y) 类似于if(condition,x,y)
arr8 = np.array([50,60,70])
print np.where(arr8>=60,u"success",u"fail")
print np.where(arr8>=60) ### 返回满足条件的数据的下标

[u'fail' u'success' u'success']
(array([1, 2]),)


In [22]:
### 排序 sort
arr2 = np.arange(10)
print arr2
np.random.shuffle(arr2) ### 乱序
print arr2
arr2.sort() ### 排序
print arr2

[0 1 2 3 4 5 6 7 8 9]
[7 0 8 3 6 1 2 4 5 9]
[0 1 2 3 4 5 6 7 8 9]


In [23]:
### all、any
### all：必须所有的都是true,才返回true,相当于and
### any: 只要有true,结果就是true,相当于or
arr = np.array([True,False,True,True,False])
print arr.all()    # False
print arr.any()    # True

False
True
